name: bali_baci_order
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: "^0.14.3"
  google_fonts: ^6.2.1
  fl_chart: ^0.71.0
  faker: ^2.2.0
  syncfusion_flutter_datepicker: ^28.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/bali-baci-logo.png
  #   - assets/
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Poppins-Italic.ttf
  #         style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/bali-baci-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21